<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.wind.integration</groupId>
        <artifactId>wind-integration</artifactId>
        <version>4.0.0-SNAPSHOT</version>
        <relativePath/>
    </parent>

    <groupId>com.wind.funds</groupId>
    <artifactId>wind-funds</artifactId>
    <packaging>pom</packaging>
    <version>${revision}</version>

    <properties>
        <revision>1.0.1-jdk21-SNAPSHOT</revision>
    </properties>

    <modules>
        <module>core</module>
        <module>ledger/ledger-face</module>
        <module>ledger/ledger-impl</module>
        <module>transaction/transaction-face</module>
        <module>transaction/transaction-impl</module>
        <module>wallet/wallet-face</module>
        <module>wallet/wallet-impl</module>
        <module>tests</module>
        <module>dependencies</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.capte.third.sdk</groupId>
                <artifactId>capte-third-sdk-dependencies</artifactId>
                <version>1.0.1-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.capte.domain</groupId>
                <artifactId>capte-domain-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.capte.domain</groupId>
                <artifactId>catep-infrastructure-dal</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>wind-funds-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>wind-funds-ledger-face</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>wind-funds-ledger-impl</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>wind-funds-transaction-face</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>wind-funds-transaction-impl</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>wind-funds-wallet-face</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>wind-funds-wallet-impl</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>wind-funds-tests</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.mybatis-flex</groupId>
            <artifactId>mybatis-flex-processor</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
