<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.wind.funds</groupId>
        <artifactId>capte-funds</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>capte-funds-tests</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.wind.funds</groupId>
            <artifactId>capte-funds-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.wind.funds</groupId>
            <artifactId>capte-funds-ledger-impl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.wind.funds</groupId>
            <artifactId>capte-funds-transaction-impl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.wind.funds</groupId>
            <artifactId>capte-funds-reconciliation-impl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.wind.funds</groupId>
            <artifactId>capte-funds-governance-impl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.wind.funds</groupId>
            <artifactId>capte-funds-wallet-impl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.wind.integration</groupId>
            <artifactId>wind-infra-commons</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.skyscreamer</groupId>
                    <artifactId>jsonassert</artifactId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.wind.tools</groupId>
            <artifactId>h2-functions-for-mysql</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.wind.middleware</groupId>
            <artifactId>wind-server</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.co.jemos.podam</groupId>
            <artifactId>podam</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.wind.tools</groupId>
            <artifactId>mybatis-flex-codegen</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.mybatis-flex</groupId>
            <artifactId>mybatis-flex-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.codemonstur</groupId>
            <artifactId>embedded-redis</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>report-aggregate</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/site/jacoco</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
