<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.wind.funds</groupId>
        <artifactId>capte-funds</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>capte-funds-dependencies</artifactId>
    <packaging>pom</packaging>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-fx-impl</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-ledger-face</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-ledger-impl</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-transaction-face</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-transaction-impl</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-reconciliation-face</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-reconciliation-impl</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-governance-face</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-governance-impl</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-wallet-face</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.wind.funds</groupId>
                <artifactId>capte-funds-wallet-impl</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
